#!/bin/sh
exedir="/usr/local/ghc-7.0.3/lib/ghc-7.0.3"
exeprog="ghc-stage2"
executablename="$exedir/$exeprog"
datadir="/usr/local/ghc-7.0.3/share"
bindir="/usr/local/ghc-7.0.3/bin"
topdir="/usr/local/ghc-7.0.3/lib/ghc-7.0.3"
pgmgcc=$(which gcc)
executablename="$exedir/ghc"
exec "$executablename" -B"$topdir" -pgmc "$pgmgcc" -pgma "$pgmgcc" -pgml "$pgmgcc" -pgmP "$pgmgcc -E -undef -traditional" ${1+"$@"}
